export const products = [
    {
        type: "Dog",
        name: "Bradley",
        adoptionStatus: "Adopted",
        picture: "https://images.dog.ceo/breeds/weimaraner/n02092339_3804.jpg",
        height: 14,
        weight: 75,
        color: "White/Blue",
        bio: "",
        hypoallergnic: false,
        dietery: [],
        breed: "Pit Bull Mix",
    },
    {
        type: "Dog",
        name: "Megatron",
        adoptionStatus: "Adopted",
        picture:
            "https://images.dog.ceo/breeds/waterdog-spanish/20180706_194432.jpg",
        height: 44,
        weight: 14,
        color: "Red",
        bio: "",
        hypoallergnic: true,
        dietery: [],
        breed: "Dachshund/Chihuahua Shorthair",
    },
    {
        type: "Cat",
        name: "Rajah",
        adoptionStatus: "Adopted",
        picture: "https://cdn2.thecatapi.com/images/MTY2MjcxMw.jpg",
        height: 4,
        weight: 65,
        color: "Brown Tabby",
        bio: "",
        hypoallergnic: true,
        dietery: [],
        breed: "Domestic Shorthair Mix",
    },
    {
        type: "Cat",
        name: "Pebbles",
        adoptionStatus: "Adopted",
        picture: "https://cdn2.thecatapi.com/images/c73.jpg",
        height: 84,
        weight: 75,
        color: "Calico",
        bio: "",
        hypoallergnic: true,
        dietery: [],
        breed: "Domestic Shorthair Mix",
    },
    {
        type: "Dog",
        name: "Johnny",
        adoptionStatus: "Adopted",
        picture:
            "https://images.dog.ceo/breeds/terrier-norwich/n02094258_3298.jpg",
        height: 66,
        weight: 88,
        color: "Blue/White",
        bio: "",
        hypoallergnic: true,
        dietery: [],
        breed: "Pit Bull",
    },
    {
        type: "Cat",
        name: "Miso",
        adoptionStatus: "Adopted",
        picture: "https://cdn2.thecatapi.com/images/ake.png",
        height: 26,
        weight: 8,
        color: "Brown Tabby/White",
        bio: "",
        hypoallergnic: false,
        dietery: [],
        breed: "Domestic Shorthair Mix",
    },
    {
        type: "Cat",
        name: "Lucky Charm",
        adoptionStatus: "Adopted",
        picture: "https://cdn2.thecatapi.com/images/b7a.jpg",
        height: 10,
        weight: 69,
        color: "Orange Tabby",
        bio: "",
        hypoallergnic: true,
        dietery: [],
        breed: "Domestic Shorthair Mix",
    },
];
